CREATE TABLE IF NOT EXISTS `users` (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    password VARCHAR(32) NOT NULL,
    salt     VARCHAR(32) NOT NULL,
    valid    TINYINT(1) DEFAULT 1 NOT NULL
);